
plugins:
  - jekyll-readme-index

readme_index:
  enabled: true
  remove_originals: false

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Custom settings
title: Curriculum Design Portfolio
description: Excerpts and samples taken from non-proprietary courses.

# Google Fonts
google_fonts: "https://fonts.googleapis.com/css2?family=Overpass:wght@300;400;600&display=swap"
