name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on main branch pushes

permissions:
  contents: write  # Ensure write permissions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with submodules
        uses: actions/checkout@v3
        with:
          submodules: true  # Fetch submodule content

      - name: Copy submodule contents
        run: |
          mkdir -p ai-api-integration
          cp -R AI-API-Integration/* ai-api-integration/
          
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Deploying to GitHub Pages" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
