name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (if using a static site generator)
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version if needed

      - name: Install dependencies (if using a static site generator)
        run: |
          npm install  # Adjust this command based on your setup

      - name: Build the project (if using a static site generator)
        run: |
          npm run build  # Adjust this command based on your setup

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust this to the directory you want to publish

